Fundamentals

For all documentation find it at https://pytorch.org/

In [73]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


Intro Tensors

General Information
- Anytime that you encode data into numbers when using pytorch it is of tensor type. 
- Typically when dealing with a scalar or vector the data is usually represented as a lower case letter, but for matrix and tensor it is upper case
    - scalar(a), vector(y), MATRIX(Q),TENSOR(X) *Note this is just common practice. 

In [74]:
#most things works off tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [75]:
# a scalar has no dimensions. So we get back 0
scalar.ndim 

0

In [76]:
# To get the tensor back as a int
scalar.item()

7

In [77]:
# Vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [78]:
#vectors do have dimensions
vector.ndim

1

In [79]:
vector.shape

torch.Size([2])

In [80]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
                       
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [81]:
# The number of dimensions is equal to the number of []
MATRIX.ndim

2

Have to use print statement if there are more than one per box. 

In [82]:
# Tensor work the same way as an array
print(MATRIX[0])
MATRIX[1]

# can also be printed as a tensor
#MATRIX[0], MATRIX[1]

tensor([7, 8])


tensor([ 9, 10])

In [83]:
# the shape is equal to the number of (row,column)
MATRIX.shape

torch.Size([2, 2])

Encode each matrix in it's own pair of []. This is so the computer can see that it has 1 bracket of [x,y]. 

In [84]:
# TENSOR 
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

Here we see it action. [1 matrix of [[3,3]]]

In [85]:
TENSOR.ndim

3

In [86]:
TENSOR.shape

torch.Size([1, 3, 3])

In [87]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Random tensors are used because they most neural networks start with a set of random tensors and then adjust those numbers in a way that 
the data can be more easily represented. 

How neural networks work

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [88]:
#Create a random tensor of size(3,4) (size/shape are the same thing)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5018, 0.2626, 0.9760, 0.2006],
        [0.1033, 0.3656, 0.0740, 0.4688],
        [0.2872, 0.1267, 0.4405, 0.0334]])

In [89]:
random_tensor.ndim

2

In [90]:
random_tensor.shape

torch.Size([3, 4])

*note that having size here does not matter this is just another way of creating a tensor. 

In [91]:
#create a random tensor with a similar shape to an image tensor
random_image_size_tenor = torch.rand(size=(224,224,3))#height, width, color channels(R,G,B)
random_image_size_tenor.shape,random_image_size_tenor.ndim #This prints in a tensor format
#color channels can also be put first torch.rand(size=(3,224,224))

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [92]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [93]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [94]:
ones.dtype
#dtype = data type 
# the default data type is float

torch.float32

Creating a range of tensors and tensors-like

In [95]:
#use torch.arange() torch.range is the same thing but an out of data way to do it. 
one_to_ten = torch.arange(0,10) #includes 0 but, excludes the 10
print(one_to_ten)

#step is something is goes up by
skip_a_few = torch.arange(0,50,5)
#skip_a_few = torch.arange(start=0,end=50,step=5) this is the same thing
skip_a_few

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [96]:
# creating tensors like creates a tensor but replaces the numbers with zeros 
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

# same thing but with ones. 
ten_ones = torch.ones_like(input=skip_a_few)
ten_ones

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Tensors data type

- The tensor is default float 32 but if you need something with more precise then use float64 if less than use float 16

Three of the biggest reasons for error are:
1. Tensor not of the right data type
2. Tensor not of the right shape (linear algebra and matrix theory)
3. Tensor not on the right device
    - This happens when one of tensors is running on a cpu but the other is on gpu/tpu/cuda


In [97]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what data type is the tensor (float32 or float16)
                               device=None, #Default this uses the cpu
                               requires_grad=False) #This is for if you want pytorch to track the gradient 
float_32_tensor 

tensor([3., 6., 9.])

In [98]:
# .type(torch.half) == .type(torch.float16). *best practice use float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [99]:
float_16_tensor.type(torch.float64) *float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

Some operations may cause an error when data types don't match but not always.

In [100]:
float_16_tensor.type(torch.int32) *float_32_tensor

tensor([ 9., 36., 81.])

Getting information from the tensor.

In [101]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2623, 0.2642, 0.8172, 0.1928],
        [0.7671, 0.5103, 0.1462, 0.9365],
        [0.1445, 0.8028, 0.8509, 0.8200]])

In [102]:
some_tensor.size()

torch.Size([3, 4])

In [103]:
# these can help with checking if the tensor match. 
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2623, 0.2642, 0.8172, 0.1928],
        [0.7671, 0.5103, 0.1462, 0.9365],
        [0.1445, 0.8028, 0.8509, 0.8200]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [104]:
device_tensor = torch.rand(3,3)
device_tensor

tensor([[0.4502, 0.3993, 0.4856],
        [0.0008, 0.0459, 0.2773],
        [0.5888, 0.3622, 0.6680]])

In [105]:
# Check if cuda(gpu) is available.
#moves the device to cuda(gpu)
if torch.cuda.is_available():
    print("Ready to go.")
    device = torch.device("cuda")
else:
    print("Failed to load")
    device = torch.device("cpu")
device_tensor = torch.device(device)
device_tensor

Ready to go.


device(type='cuda')

In [106]:
#moving bach to cpu
device_tensor = torch.device("cpu")
device_tensor

device(type='cpu')

### Manipulating Tensors(Tensor Operations)

Tensor operations include:

Addition

Subtraction

Multiplication(element-wise)

Division

Matrix multiplication


In [107]:
tensor = torch.tensor([1,2,3])
print(f"Adding: {tensor + 10}")
print(f"Subtraction: {tensor - 10}")
print(f"Multiply: {tensor * 2}")
print(f"Divide: {tensor / 10}")

Adding: tensor([11, 12, 13])
Subtraction: tensor([-9, -8, -7])
Multiply: tensor([2, 4, 6])
Divide: tensor([0.1000, 0.2000, 0.3000])


In [108]:
#pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

# Matrix multiplication
1. element wise (mulitply by a scalar)
2. Dot product

**(rows,cols)*

This is the the same as from linear algebra and matrix theroy. 
# Rules
1. the inner dimensions must match. for example:
    
    [1, 2] @ [3, 4] will not compute 
    
    [5, 6] @ [6, 8] will compute
2. The resulting matrix will have the shape of the outer dimensions for example:
    
    (3,4) @ (4,3) The new shape will be (3,3)
    
    (3,5) @ (5,1) the new shape will be (3,1)

In [109]:
#example
torch.matmul(torch.rand(3,5), torch.rand(5,1))

tensor([[1.9491],
        [1.4992],
        [2.1190]])

In [110]:
# Element-wise multiplication
tensor * tensor 

tensor([1, 4, 9])

In [111]:
# dot product
print(tensor," * ",  tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3])  *  tensor([1, 2, 3])


tensor(14)

Dot product does (1 * 1)+(2 * 2)+(3 * 3)

Timing how long each of the codes take. 

In [112]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 544 µs


In [113]:
%%time 
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [114]:
#also another way to do matrix multiplication dot product
#this takes the same amount of time as above
tensor @ tensor

tensor(14)

In [115]:
%%time
tensor @ tensor

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

Matrix multiplication shape errors

In [116]:
#This will give an error because shapes do not match 
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#tensor_A @ tensor_B
#torch.mm(tensor_A, tensor_B) #mm = matmul

# Multiplying matrix's with shapes that do not match. 

By using a transpose you can manipulate the shape of the matrix. This will switch the axis of the given tensor

In [117]:
#.T is the transpose of the original matrix
tensor_A.T, tensor_A

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [118]:
# we can see that the transpose will change the dimensions of the matrix by checking the shape
tensor_A.T.shape, tensor_A.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [119]:
tensor_A @ tensor_B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [120]:
new_tensor = torch.mm(tensor_A, tensor_B.T)
print(f"This will give the new shape of: {new_tensor.shape}")

This will give the new shape of: torch.Size([3, 3])


# Tensors, min, max, mean, sum. (tensor aggregation)

In [121]:
import random
x = torch.arange(0,100,random.randint(5,10))
x

tensor([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [122]:
#Finding the max min and sum
max = x.max()
min = x.min()
sum = x.sum()

#another way torch.min(x)... 

print("Maximum value in the array: ", max)
print("Minimum value in the array: ", min)
print("Sum of all elements in the array: ", sum)

Maximum value in the array:  tensor(96)
Minimum value in the array:  tensor(0)
Sum of all elements in the array:  tensor(816)


In [123]:
# For mean process is slightly different, you have to do this because the datatype's do not match. 
# when computing it normally it will give you a long but wants a float so you get an error.
mean = torch.mean(x.type(torch.float))
mean2 = x.type(torch.float32).mean()
print(f"The mean value in the tensor is: {mean}")
print(f"Second way to get the mean value in the tensor is: {mean2}")

The mean value in the tensor is: 48.0
Second way to get the mean value in the tensor is: 48.0


In [124]:
#finding the position of where the max/min values are 
print(x.shape)
x.argmin(), x.argmax(),

torch.Size([17])


(tensor(0), tensor(16))

In [125]:
position_max = torch.argmax(x)
position_max

tensor(16)

# Reshaping, Stacking, Squeezing, Unsqueezing, and Permuting tensor

* Reshaping - reshapes the tensor in your desired way

* View - Returns a view of an input tensor of certain shape but keeps the same memory as the original tensor. 

* Stacking - combines multiple tensor on top of each other
    - .vstack (vertically stacking)
    - .hstack (horizontally stacking)

* Squeezing - removes single-dimensional entries from the shape of a tensor.

* Unsqueezing - adds a new dimension of size 1 to the tensor at the specified position.

* Permute - return a view of the input with dimensions permuted(swapped) in a certain way



In [126]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [127]:
# Adding a dimension
# x_reshaped = x.reshape(1,7) this won't work because you're trying to push in 9 dimensions into 7 places
x_reshaped = x.reshape(1,9) # pushing 9 inputs into 1 dimension
x_own_tensors = x.reshape(9,1) # This will put 9 inputs into a their own tensor's 
print(x_reshaped)

print(f"Own tensors: {x_own_tensors.shape}")
print(f"Reshaped: {x_reshaped.shape}")
print(f"Normal: {x.shape}")
print(x_own_tensors)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Own tensors: torch.Size([9, 1])
Reshaped: torch.Size([1, 9])
Normal: torch.Size([9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [128]:
# As long as the .reshape(x,y) multiply equal to the shape/size of the original it can be reshaped as such
x_test_reshape = x.reshape(3,3)
x_test_reshape, x_test_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [129]:
# view will show the same thing as reshape, BUT remember that view keeps the same memory as the original. 
# WHATEVER CHANGES ARE MADE TO THE OBJECT IN VIEW WILL CHANGE THE ORIGINAL 
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [130]:
# for example if i change the second number for z, then the the second number in x will change as well. 
z[:,1] = 5
z,x

(tensor([[1., 5., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 5., 3., 4., 5., 6., 7., 8., 9.]))

vstack will stack the following on top of one another in their own tensors.

hstack will merge the following into one tensor

(v/h)stack([x,x,x], dim=0) 0 is the same as vstack and 1 will take each number and repeat as a tensor. 

In [131]:
# Stacking tensors

x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[1., 5., 3., 4., 5., 6., 7., 8., 9.],
        [1., 5., 3., 4., 5., 6., 7., 8., 9.],
        [1., 5., 3., 4., 5., 6., 7., 8., 9.],
        [1., 5., 3., 4., 5., 6., 7., 8., 9.]])

In [132]:
# drops all dimension that have a size of 1. 
x_one_dim = x.reshape(1,9)
x_squeezed = torch.squeeze(x_one_dim)

print(f"with dimension: {x_one_dim}")
print(f"Removed dimension: {x_squeezed}")

with dimension: tensor([[1., 5., 3., 4., 5., 6., 7., 8., 9.]])
Removed dimension: tensor([1., 5., 3., 4., 5., 6., 7., 8., 9.])


In [133]:
# adds in dimensions at the chosen position
# must be in range of [-2, 1]
# 1/-1 puts all in their own tensors
# 0/-2 puts all in one tensor
x_unsqueezed = torch.unsqueeze(x,1)
x_unsqueezed, x_unsqueezed.shape, x, x.shape

(tensor([[1.],
         [5.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 tensor([1., 5., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [134]:
# to permute a tensor is the same as to swap the dimensions. 
x_permute = torch.rand(3,2,4)
print(f" original shpae is: {x_permute.shape}")

# after permute
print(f" After permute: {torch.permute(x_permute,(1,2,0)).shape}")
#another way to do it. use this way
permuted = x_permute.permute((1,2,0))

 original shpae is: torch.Size([3, 2, 4])
 After permute: torch.Size([2, 4, 3])


# Indexing

Indexing with pytorch is the same as indexing in numpy

first number is all elements in that dimension
    
second number selects rows

third number selects the columns

In [135]:
x = torch.arange(1,10,).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [136]:
# Index on tensor
print(x[0]) # first zero gets inside the first set of brackets
print(x[0,0]) # second zero give back the 0 dimensions of the x[0] tensor 
print(x[0,0,0]) # third zero give back the 0 dimensions of the x[0,0]

# to get back a certain value like 9
print(x[0,2,2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(9)


In [137]:
# The : gets all the the targets dimension
x[:,0] 

tensor([[1, 2, 3]])

In [138]:
x[:,:,1]

tensor([[2, 5, 8]])

In [139]:
x[0,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [140]:
#all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [141]:
# index 0 of 0th and 1st dimension and all values of the 2nd dimension
x[0, 0,:]

tensor([1, 2, 3])

In [142]:
x[0,:,0]

tensor([1, 4, 7])

In [143]:
# return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

# Pytorch tensors and numpy

Numpy is a popular scientific python numerical library. 

And because of this, pytorch hasa functionality to interact with it. When transferring the data it will be transferred in the same data type as it is currently stored in.

* Data in numpy, want input torch tensor -> torch.from_numpy(ndarray)
* Pyorch tensor -> numpy -> torch.tensor.numpy()

In [144]:
# numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #.type(torch.float32)      changing the datatype
array, tensor, tensor.dtype

RuntimeError: Numpy is not available

* numpy uses a default of float64

In [ ]:
# form tenosr to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

These two do not share the same memory

# Reproducing (taking out randomness)

To reduce the amount of randomness in neural networks and pytorch comes the concept of a random seed. essentially what the radom seed does is "flavor" the randomness

In [ ]:
# random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A) 
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)
#they will almost never be equal

tensor([[0.1089, 0.3158, 0.4755, 0.3832],
        [0.2010, 0.6830, 0.3285, 0.3106],
        [0.8588, 0.1114, 0.2163, 0.6617]])
tensor([[0.7375, 0.0613, 0.0378, 0.9382],
        [0.2896, 0.6513, 0.3586, 0.7292],
        [0.0442, 0.3551, 0.0371, 0.7083]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# How to make it reproducible

# first set a random seed
RANDOM_SEED = 13

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

# YOU MUST RESET THE RANDOM_SEED EACH AND EVERY TIME YOU USE A NEW RANDOM METHOD

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.0918, 0.4794, 0.8106, 0.0151],
        [0.0153, 0.6036, 0.2318, 0.8633],
        [0.9859, 0.1975, 0.0830, 0.4253]])
tensor([[0.0918, 0.4794, 0.8106, 0.0151],
        [0.0153, 0.6036, 0.2318, 0.8633],
        [0.9859, 0.1975, 0.0830, 0.4253]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors with the gpu

This happens with the help of nvidia hardware, CUDA, and pytorch.

If you don't want to use your own gpu you can use:
 1. google colab
 2. OSC or juptyr notebook
 3. AWS or Azure notebook.

In [ ]:
# setting up device agnostic code
# if gpu is available then use it
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [ ]:
# number of device that can be used
# can be useful is running multiple models and run them on different ones. 
torch.cuda.device_count()

1

In [ ]:
# putting tensors or gpu for faster performance
tensor = torch.tensor([1,2,3])
tensor, tensor.device

# tensors default to cpu but can be moved to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Not all things work with the gpu. For example numpy does not work with gpus.

In [ ]:
# moves back to cpu
tensor_on_gpu.cpu().numpy()
tensor_on_gpu.cpu().device

device(type='cpu')