Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2+cpu


Intro Tensors

General Information
- Anytime that you encode data into numbers when using pytorch it is of tensor type. 
- Typically when dealing with a scalar or vector the data is usually represented as a lower case letter, but for matrix and tensor it is upper case
    - scalar(a), vector(y), MATRIX(Q),TENSOR(X) *Note this is just common practice. 

In [4]:
#most things works off tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# a scalar has no dimensions. So we get back 0
scalar.ndim 

0

In [9]:
# To get the tensor back as a int
scalar.item()

7

In [6]:
# Vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
#vectors do have dimensions
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
                       
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
# The number of dimensions is equal to the number of []
MATRIX.ndim

2

Have to use print statement if there are more than one per box. 

In [43]:
# Tensor work the same way as an array
print(MATRIX[0])
MATRIX[1]

# can also be printed as a tensor
#MATRIX[0], MATRIX[1]

tensor([7, 8])


tensor([ 9, 10])

In [14]:
# the shape is equal to the number of (row,column)
MATRIX.shape

torch.Size([2, 2])

Encode each matrix in it's own pair of []. This is so the computer can see that it has 1 bracket of [x,y]. 

In [28]:
# TENSOR 
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

Here we see it action. [1 matrix of [[3,3]]]

In [29]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

In [31]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Random tensors are used because they most neural networks start with a set of random tensors and then adjust those numbers in a way that 
the data can be more easily represented. 

How neural networks work

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [38]:
#Create a random tensor of size(3,4) (size/shape are the same thing)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2570, 0.4163, 0.0803, 0.3404],
        [0.6798, 0.4766, 0.5612, 0.7657],
        [0.4257, 0.2646, 0.2004, 0.7561]])

In [33]:
random_tensor.ndim

2

In [39]:
random_tensor.shape

torch.Size([3, 4])

*note that having size here does not matter this is just another way of creating a tensor. 

In [45]:
#create a random tensor with a similar shape to an image tensor
random_image_size_tenor = torch.rand(size=(224,224,3) #height, width, color channels(R,G,B)
random_image_size_tenor.shape,random_image_size_tenor.ndim #This prints in a tensor format
#color channels can also be put first torch.rand(size=(3,224,224))

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [46]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
ones.dtype
#dtype = data type 
# the default data type is float

torch.float32

Creating a range of tensors and tensors-like

In [55]:
#use torch.arange() torch.range is the same thing but an out of data way to do it. 
one_to_ten = torch.arange(0,10) #includes 0 but, excludes the 10
print(one_to_ten)

#step is something is goes up by
skip_a_few = torch.arange(0,50,5)
#skip_a_few = torch.arange(start=0,end=50,step=5) this is the same thing
skip_a_few

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [58]:
# creating tensors like creates a tensor but replaces the numbers with zeros 
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

# same thing but with ones. 
ten_ones = torch.ones_like(input=skip_a_few)
ten_ones

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Tensors data type

- The tensor is default float 32 but if you need something with more precise then use float64 if less than use float 16

Three of the biggest reasons for error are:
1. Tensor not of the right data type
2. Tensor not of the right shape (linear algebra and matrix theory)
3. Tensor not on the right device
    - This happens when one of tensors is running on a cpu but the other is on gpu/tpu/cuda


In [61]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what data type is the tensor (float32 or float16)
                               device=None, #Default this uses the cpu
                               requires_grad=False) #This is for if you want pytorch to track the gradient 
float_32_tensor 

tensor([3., 6., 9.])